Feat/organization
fleye-me/Fleye-api-users pull request #2
Opened 2022-04-22 18:14 UTC by godoyjulia

Criação de data-helper.js para separar código que envolve criação de commandos SQL.
Melhorando a escrita do código para tornar mais legível.

2022-04-22 19:12 UTC, joaoschaab commented on data/companies.json
> +  "users": [
pq esse arquivo ta aqui?

2022-04-22 19:13 UTC, joaoschaab commented on data/index.js
> +  password: 'admin',
passar essas configurações para variável de ambiente

2022-04-22 19:15 UTC, joaoschaab commented on src/common/data-helper.js
> +function auxGet(query) {
o que essa funçao faz?

2022-04-22 19:16 UTC, joaoschaab commented on src/connection/queries.js
>    console.log(rawQuery);
remover console.log

2022-04-22 19:34 UTC, joaoschaab commented on src/connection/queries.js
>    console.log(rawQuery);
console

2022-04-22 19:34 UTC, joaoschaab commented on src/connection/queries.js
>    console.log(rawQuery);
console

2022-04-22 19:34 UTC, joaoschaab commented on src/routes/companies.js
> +  console.log(newCompany);
remover ocnsole.log

2022-04-22 19:35 UTC, joaoschaab commented on src/routes/companies.js
> +  let user = data.companies;
VISH

2022-04-25 16:30 UTC, godoyjulia commented on src/common/data-helper.js
> +function auxGet(query) {
cria o comando select com os filtros/ordenaçao/limites

2022-04-25 16:33 UTC, godoyjulia commented on data/companies.json
> +  "users": [
opa..esqueci de deletar

2022-04-25 17:46 UTC, joaoschaab commented on src/common/data-helper.js
> +function auxGet(query) {
olhando pelo nome da função dificilmente a gente vai entender o que ela faz, uma sugestao entao nesse caso seria:

```
function buildSQLGetRawQuery ()
```

2022-04-25 17:47 UTC, joaoschaab requested changes
* Ler credenciais de variavel de ambiente
* Remover arquivos nao utilizados
* Melhorar o nome das funções que tem 'aux' no nome

2022-04-28 20:32 UTC, merged